// Package harness is the rig every construction is measured in. It contains no
// construction-specific logic and reimplements no hash: a construction describes
// itself, and the harness does the identical thing to all of them. Four layers, in
// dependency order:
//
//   - **The unit of work.** A [Case] is one named circuit over one field, with the
//     closures to build, evaluate and (via [Count]) compile it. [Solve] checks one
//     against a reference [Vector]; prove.go runs the real prover ([Measure]:
//     setup, prove, verify, timings and sizes) with witnesses generated by
//     evaluating the circuit's own Eval under gnark's native engine.
//   - **The registry.** An [Instance] (one parameter set over one field, declared by
//     a construction) expands into [Target]s — one per (instance × mode), each
//     carrying its Case plus the labels that identify it. [Pick] names one instance
//     out of a construction's registry; [Filter] selects targets by label.
//   - **The jobs.** [Message] and [Merkle] build a Case for a *whole circuit* of
//     many hash calls rather than one, which is where a lookup table's setup
//     amortizes and a mode's rate decides the call count.
//   - **The runners.** [RunTests] and [RunBench] are the testing.T/B glue.
//
// This is the single place to change if the methodology changes. What it must never
// learn is which hashes exist: the list of constructions lives in package registry,
// which imports this one (the constructions do too), never the other way round.
package harness

import (
	"embed"
	"encoding/json"
	"fmt"
	"io/fs"
	"math/big"
	"path"

	"github.com/consensys/gnark/constraint"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/r1cs"
	"github.com/consensys/gnark/frontend/cs/scs"
	"github.com/consensys/gnark/test"
)

// Backend selects which constraint system a circuit compiles to, and hence which
// cost metric GetNbConstraints reports. R1CS is the primary SoK metric (the
// Groth16 arithmetization: each constraint is one rank-1 product); PLONK compiles
// to gnark's sparse constraint system (SCS), whose gate count is PLONK's cost
// (each gate a fan-in-2 add/mul). The two counts are different units, so compare
// each backend against itself — never an R1CS count against a PLONK one.
//
// A Backend also carries the proof system that consumes its constraint system
// (System, and the prover behind it — see prove.go), because the two were never
// independent: an R1CS is what Groth16 proves, an SCS what PLONK proves. Both
// fields are set by the two Backend values below, so a Backend remains a plain
// comparable value that callers pass around by copy.
type Backend struct {
	Name    string // "r1cs" or "plonk"
	Metric  string // unit label for CSV headers / bench metrics: "constraints" or "gates"
	System  string // the proof system over it: "groth16" or "plonk"
	builder frontend.NewBuilder
	proofs  proofSystem
}

var (
	// R1CS is the default backend and the headline comparison metric.
	R1CS = Backend{
		Name: "r1cs", Metric: "constraints", System: "groth16",
		builder: r1cs.NewBuilder[constraint.U64], proofs: groth16System{},
	}
	// PLONK reports the SCS gate count — the same circuits, no changes required,
	// since every construction is written against the backend-agnostic frontend.API.
	PLONK = Backend{
		Name: "plonk", Metric: "gates", System: "plonk",
		builder: scs.NewBuilder[constraint.U64], proofs: plonkSystem{},
	}
)

// Case is one measurable configuration of a construction: a named circuit over a
// fixed field.
//
// Build returns the circuit wired for the given input/output slices. It is
// called two ways: with nil-valued slices of the right length to get a
// compilation stub (structure only), and with concrete values to get a witness
// assignment. Modelling both input and output as slices keeps the harness
// agnostic to the mode of operation — a sponge hash sets OutputSize to 1, a bare
// permutation would set it to the state width — so the same harness serves all
// four construction types.
//
// Eval is the same computation the circuit asserts, exposed as a plain
// input->output function of in-circuit values. Counting and vector-solving do
// not need it, but proving does: a prover needs a *satisfying* witness, and the
// circuits assert `Build`'s out against the computed result, so an arbitrary
// (generated) input has no usable output until something evaluates it. Eval is
// that something — [Evaluate] runs it under gnark's native test engine, which
// makes generated-input witnesses work for every target without a single
// out-of-circuit reimplementation. It may be nil, in which case only
// reference-vector witnesses are available.
type Case struct {
	Name       string
	Field      *big.Int
	InputSize  int
	OutputSize int
	Build      func(in, out []frontend.Variable) frontend.Circuit
	Eval       func(api frontend.API, in []frontend.Variable) []frontend.Variable
}

// Count compiles the case with the given backend and returns its cost — R1CS
// constraints or PLONK gates. The count is deterministic, so this is the source
// of truth for the cross-hash comparison (used by cmd/bench and RunBench).
func Count(b Backend, c Case) (int, error) {
	ccs, err := compile(b, c)
	if err != nil {
		return 0, err
	}
	return ccs.GetNbConstraints(), nil
}

// compile builds the case's compilation stub — the circuit structure, with
// nil-valued wires — and compiles it to the backend's constraint system. Both
// Count and the proving pipeline start here, so they always measure and prove
// the identical circuit.
func compile(b Backend, c Case) (constraint.ConstraintSystem, error) {
	stub := c.Build(make([]frontend.Variable, c.InputSize), make([]frontend.Variable, c.OutputSize))
	ccs, err := frontend.Compile(c.Field, b.builder, stub)
	if err != nil {
		return nil, fmt.Errorf("harness: compile %s (%s): %w", c.Name, b.Name, err)
	}
	return ccs, nil
}

// Vector is a reference input/output pair for a named instance and mode. Field
// elements are given as integer literals ("0x.." hex or plain decimal), reduced
// mod the instance field. Mode ("permutation", "sponge", "jive-2", ...) selects
// which target the vector belongs to; [Target.MatchesVector] is the rule.
type Vector struct {
	Instance string   `json:"instance"`
	Mode     string   `json:"mode"`
	Input    []string `json:"input"`
	Output   []string `json:"output"`
}

// Solve builds the witness for v and asserts the case's circuit is satisfied.
// It does not run a full prover: test.IsSolved checks constraint satisfaction,
// which is exactly what validates correctness against a reference vector.
func Solve(c Case, v Vector) error {
	in, err := ParseElements(v.Input)
	if err != nil {
		return err
	}
	out, err := ParseElements(v.Output)
	if err != nil {
		return err
	}
	stub := c.Build(make([]frontend.Variable, len(in)), make([]frontend.Variable, len(out)))
	assignment := c.Build(variables(in), variables(out))
	return test.IsSolved(stub, assignment, c.Field)
}

// EmbeddedVectors returns every reference vector in the JSON files under testdata/
// of an embedded filesystem — what each construction's Vectors() is:
//
//	//go:embed testdata/*.json
//	var testdata embed.FS
//
//	func Vectors() []harness.Vector { return harness.EmbeddedVectors("gmimc", testdata) }
//
// The vectors are embedded rather than read from disk so they travel with the
// package and load from any working directory (the cross-construction tests in
// registry/ depend on that). name only labels panics.
//
// It panics rather than returning an error: the data is compiled in, so a missing
// directory or malformed file is a build-time programming error, not a runtime
// condition a caller could handle.
func EmbeddedVectors(name string, fsys embed.FS) []Vector {
	entries, err := fs.ReadDir(fsys, "testdata")
	if err != nil {
		panic(fmt.Sprintf("%s: reading embedded testdata: %v", name, err))
	}
	var all []Vector
	for _, e := range entries {
		if e.IsDir() || path.Ext(e.Name()) != ".json" {
			continue
		}
		data, err := fsys.ReadFile("testdata/" + e.Name())
		if err != nil {
			panic(fmt.Sprintf("%s: reading %s: %v", name, e.Name(), err))
		}
		var file struct {
			Vectors []Vector `json:"vectors"`
		}
		if err := json.Unmarshal(data, &file); err != nil {
			panic(fmt.Sprintf("%s: parsing %s: %v", name, e.Name(), err))
		}
		all = append(all, file.Vectors...)
	}
	return all
}

// ParseElements parses a vector's integer literals ("0x.." hex or decimal) into
// field elements. They stay *big.Int rather than becoming frontend.Variable
// straight away because a prover's witness and a native evaluation both need the
// values themselves; variables() lifts them when a circuit assignment is what is
// wanted. Exported because a caller comparing a vector against [Evaluate] needs
// the same parse.
func ParseElements(ss []string) ([]*big.Int, error) {
	out := make([]*big.Int, len(ss))
	for i, s := range ss {
		v, ok := new(big.Int).SetString(s, 0)
		if !ok {
			return nil, fmt.Errorf("harness: invalid field element %q", s)
		}
		out[i] = v
	}
	return out, nil
}
