// Package skyscraper implements the Skyscraper permutation (eprint 2024/1553) as
// a gnark circuit, ported from the reilabs reference
// (github.com/reilabs/gnark-skyscraper) into this framework's structure and
// validated byte-exact against the Python reference's known-answer vectors — with
// the round constants generated by the reference framework (SHA-256 sampler), not
// taken from the reilabs source.
//
// Skyscraper is a "type-3" design and the outlier of this repo: a 2-branch Feistel
// (no linear layer, no power-map S-box) whose two round functions alternate by
// round index:
//   - Square: x -> x^2 * MontRInv           (a field square times a Montgomery constant)
//   - Bar:    x -> recompose(sbox(rotate(decompose(x))))  (a wordwise lookup S-box)
//
// The Bar is the genuinely new gadget: it canonically decomposes the field element
// into WordBits-bit words (algebra.CanonicalDecomposeExternalWordRange), cyclically
// rotates them, and applies a word S-box via a lookup table — which also range-checks
// the words, since looking one up already binds it to the table's index domain. Only
// the canonicity check needs a range check of its own. WordBits is 8 (byte words, the
// reference) or 16 (two-byte words, Instances16); both give byte-identical output.
//
// # Width
//
// A BRANCH IS ONE ELEMENT OF GF(p^n), so the state is t = 2n base-field elements and n
// is the only width knob the design has — there is no linear layer to widen. Both
// implemented degrees are here:
//
//	n = 1  t = 2  the prime field; the reilabs reference and SKYSCRAPER_<FIELD>_N1
//	n = 2  t = 4  GF(p^2) = F_p[X]/(X^2 + Beta); SKYSCRAPER_<FIELD>_N2
//
// Only two things see n. The Square becomes a squaring in GF(p^n) — see [engine.square],
// which is where the extension modulus is used and where the whole per-round cost
// difference lives. The Bar does NOT become an extension operation: it is a map on the
// integer representation, so it decomposes each coordinate separately and rotates the
// CONCATENATED digits, which is the only place the coordinates mix. Everything else —
// the Feistel, the round schedule, the S-box table — is per-coordinate or unchanged.
//
// File layout mirrors the Python reference framework (skyscraper/):
//   - skyscraper.go — the permutation round function (Feistel: Square/Bar rounds)  ≈ hash.py
//   - params.go     — parameter generation and sanity checks                       ≈ params.py
//   - instances.go  — concrete instances + harness/mode wiring                     ≈ instances.py
package skyscraper

import (
	"fmt"
	"math/big"

	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/std/lookup/logderivlookup"
	"github.com/consensys/gnark/std/rangecheck"
	"github.com/zkhash-sok/gnark-hashes/algebra"
	"github.com/zkhash-sok/gnark-hashes/permutation"
)

// Permutation is the in-circuit Skyscraper permutation.
type Permutation struct {
	params *Parameters
}

var _ permutation.Permutation = (*Permutation)(nil)

// NewPermutation returns a Skyscraper permutation for the given parameters.
func NewPermutation(params *Parameters) *Permutation { return &Permutation{params: params} }

// Width returns the Feistel state width t = 2n, in base-field elements.
func (p *Permutation) Width() int { return p.params.T }

// Permute applies the Skyscraper Feistel. The state is two branches of n base-field
// coordinates each, state = xL || xR; each round replaces (xL, xR) with
// (xR + roundFunc(xL) + rc, xL), coordinatewise, where roundFunc is Square or Bar
// (by round index). The first and last rounds have zero constants. Mirrors
// Skyscraper.permutation in the reference skyscraper/hash.py.
//
// The round constant is added in the Feistel addition rather than inside the branch
// map: a PLONK gate carries a constant selector, so `Add(xR, f, rc)` is the one gate
// the Feistel needs anyway, where adding rc to f first would cost a second. That is n
// gates a round at any degree, so the Feistel glue is t/2 * R and not more.
func (p *Permutation) Permute(api frontend.API, state []frontend.Variable) []frontend.Variable {
	if len(state) != p.params.T {
		panic(fmt.Sprintf("skyscraper: state size %d, expected %d", len(state), p.params.T))
	}
	e := newEngine(api, p.params)
	n := p.params.N

	l := append([]frontend.Variable(nil), state[:n]...)
	r := append([]frontend.Variable(nil), state[n:]...)
	for i := 0; i < p.params.R; i++ {
		f := e.roundFunc(l, i)
		next := make([]frontend.Variable, n)
		for j := range next {
			next[j] = api.Add(r[j], f[j], e.params.Rcons[i][j])
		}
		l, r = next, l
	}

	out := make([]frontend.Variable, 0, p.params.T)
	return append(append(out, l...), r...)
}

// engine holds the in-circuit state that must be built once and reused across
// every Bar call. It mirrors the role of the reilabs Skyscraper struct.
//
// The word S-box table is queried directly to apply the S-box, and every Bar word is
// range-checked for free by being looked up in it. The one range check the Bar cannot
// get that way — the canonicity difference, which is not a word of the input — goes to
// gnark's std/rangecheck (rchk), whose own table this therefore also pays for; see
// bar for why the second table is nevertheless cheaper than reusing this one.
//
// Its scope is the whole *compilation*, not one Permute call: the table costs one
// constraint per entry (2^WordBits of them), so a circuit calling the permutation
// k times must pay for those entries once, not k times. algebra.Shared caches it
// per compilation, which is what lets the lookup argument amortize over a Merkle
// tree or a long sponge absorption — the very thing the 16-bit-word variant needs
// to be worth its 2^16 table. Both extension degrees share one table per (field,
// word size) for the same reason: the table is indexed by a WORD, and a word does
// not know which coordinate it came from.
type engine struct {
	api    frontend.API
	params *Parameters
	sbox   logderivlookup.Table
	rchk   frontend.Rangechecker
}

// engineKey identifies one engine per (compilation, parameter set). Two instances
// over different fields or word sizes have different tables, so they must not
// share; the parameter pointer distinguishes them.
type engineKey struct{ params *Parameters }

func newEngine(api frontend.API, params *Parameters) *engine {
	return algebra.Shared(api, engineKey{params}, func() *engine {
		tbl := logderivlookup.New(api)
		for _, v := range params.SboxLUT {
			tbl.Insert(v)
		}
		return &engine{api: api, params: params, sbox: tbl, rchk: rangecheck.New(api)}
	})
}

// roundFunc is the branch map applied to the left branch in round i: Square unless
// i is a Bar round. The round constant is not added here — Permute folds it into
// the Feistel addition, where it is free.
func (e *engine) roundFunc(branch []frontend.Variable, round int) []frontend.Variable {
	if e.params.BarRounds[round] {
		return e.bar(branch)
	}
	return e.square(branch)
}

// square is x -> x^2 * MontRInv over the branch field GF(p^n) = F_p[X]/(X^n + Beta),
// applied to the branch's n coordinates. The Montgomery scaling is a constant, so it
// is free in both backends at every degree: it folds into a wire coefficient.
//
// n = 1 is one multiplication and nothing else. n = 2 is a squaring in GF(p^2) with
// X^2 = -Beta, and there the arithmetization has a real choice — THE ONE
// ARITHMETIZATION CHOICE THE EXTENSION INTRODUCES — because the two standard
// spellings sit on opposite sides of the two units:
//
//	schoolbook   c0 = a^2 - Beta*b^2,  c1 = 2ab               3 products, 1 sum
//	complex      c0 = (a+b)(a-Beta*b) - (1-Beta)*ab, c1 = 2ab  2 products, 3 sums
//
// The complex (Karatsuba) form reuses the product ab, which the imaginary coordinate
// needs anyway, and pays for it with the two extra WIRES its factors have to be
// materialised into — a+b and a-Beta*b. Neither is optional: a PLONK row multiplies
// two wires, not two linear expressions.
//
// Measured on BLS12-381, per square and as the whole n=2 permutation:
//
//	              per square       permutation (w8)     permutation (w16)
//	schoolbook    3 R1CS / 4 SCS   1439 / 5276          66591 / 330524
//	complex       2 R1CS / 5 SCS   1425 / 5290          66577 / 330538
//
// exactly ±1 per square across the 14 Square rounds. THE COMPLEX FORM IS WHAT SHIPS,
// for two reasons that both outlast the 14 rows. It is how the design's own literature
// counts an extension square — two multiplications — so reporting the schoolbook
// number would put Skyscraper's t=4 row 14 constraints above what its designers would
// claim, which is the same fairness argument that put Poseidon-1's partial rounds in
// their sparse factorisation (linear_layers.md §4.1). And a multiplication is charged
// by every proof system, where a fan-in-2 addition is an artifact of gnark's 3-wire
// row and gets cheaper the wider the row is (tmp_plonk_vs_r1cs.md) — so the form that
// minimises products is the one that stays right under a different backend.
//
// No third spelling reaches 2 products in 4 rows. c1 = 2ab fixes one product; the
// other must be a product of two linear forms whose b^2 coefficient is non-zero, and
// (alpha*a + gamma*b)(delta*a + eps*b) has gamma*eps != 0 only if BOTH factors are new
// values — a and b themselves cannot serve. So 2 products always costs 2 extra wires.
//
// The 4-versus-5 does not scale into anything: the whole Square layer is 28 R1CS / 70
// SCS of a ~1400 / ~5300 permutation, because this construction's cost is its Bars and
// their table (see bar), not its arithmetic.
//
// Both spellings are in square_test.go — the schoolbook one only there, since only one
// ships — where TestSquareSpellingsAgree checks they are the same map and
// TestSquareSpellingCost pins the per-square 2/5 against 3/4. That pin is not
// redundant with registry/cost_test.go: a revert to the schoolbook form would show up
// there as fourteen gates SAVED.
func (e *engine) square(branch []frontend.Variable) []frontend.Variable {
	api, rInv, field := e.api, e.params.MontRInv, e.params.Field
	if e.params.N == 1 {
		return []frontend.Variable{api.Mul(api.Mul(branch[0], branch[0]), rInv)}
	}
	md := func(x *big.Int) *big.Int { return new(big.Int).Mod(x, field) }
	beta := e.params.Beta

	a, b := branch[0], branch[1]
	ab := api.Mul(a, b)
	s := api.Mul(api.Add(a, b), api.Add(a, api.Mul(b, md(new(big.Int).Neg(beta)))))

	// c0 = (s - (1-Beta)*ab) * MontRInv, c1 = 2ab * MontRInv. Every scalar here is a
	// constant, so only the c0 sum is a gate; c1 is ab's wire rescaled.
	corr := md(new(big.Int).Neg(new(big.Int).Mul(new(big.Int).Sub(big.NewInt(1), beta), rInv)))
	return []frontend.Variable{
		api.Add(api.Mul(s, rInv), api.Mul(ab, corr)),
		api.Mul(ab, md(new(big.Int).Lsh(rInv, 1))),
	}
}

// bar is the split-and-lookup S-box on a branch: canonically decompose each of the n
// coordinates into big-endian words, apply the word S-box to each via the lookup
// table, cyclically rotate the CONCATENATED n*NumWords words left by Rot, and
// recompose each coordinate from its slice of the rotated list. (Applying the uniform
// S-box then rotating is equivalent to rotating then applying it, as the reilabs
// reference does — a position permutation commutes with an elementwise map.)
//
// The rotation is the one place the coordinates of an extension branch interact, and
// it is deliberately over the FLAT digit list, not per coordinate: Rot = NumWords/2 is
// half a coordinate's worth of words, so at n = 2 the top half of each coordinate
// lands in the other. That is the reference's `digits_flat[rot:] + digits_flat[:rot]`
// over n*m digits, and it costs nothing in circuit either way — a rotation is wire
// routing, whatever it crosses.
//
// The decomposition deliberately skips per-word range checks
// (CanonicalDecomposeExternalWordRange): each word is looked up in the 2^WordBits-
// entry S-box table just below, and that lookup already binds the word to the
// table's index domain [0, 2^WordBits) — exactly the WordBits-bit range check. So
// one lookup per word does double duty (range check + S-box), and the only residual
// range check is the single canonicity difference per COORDINATE, which is a derived
// value rather than a word and so needs e.rchk.
//
// A LOOKUP QUERY IS THE UNIT OF COST HERE, and both halves of the Bar are counted in
// them. One Bar over a 254/255-bit field is, per coordinate:
//
//	NumWords queries    S-box + word range check      16 (WordBits=16) / 32 (WordBits=8)
//	halfBits/WordBits   the canonicity range check     8               / 16
//
// i.e. 24 or 48 queries per coordinate — 24n or 48n per Bar — against ONE constraint
// per Square round for all fourteen of them (three at n = 2). Nothing else in the
// permutation is worth optimizing until the query count comes down, and the levers on
// it are WordBits (a wider word is fewer queries and a quadratically bigger table —
// see [Instances16]), the width of the canonicity check (halved by the lexicographic
// form in algebra.assertLessThanModulus), and which argument each kind of query goes
// into, which is the reason for e.rchk. NONE of them is n: the Bar is linear in the
// coordinate count, so the extension buys width at exactly proportional cost, which is
// the datum n = 2 contributes to the comparison.
//
// What a query costs depends on how wide the table it lands in is. The S-box table has
// to be TWO columns — (index, value) — so a query is a random linear combination of the
// row plus an inverse. A pure range check needs only ONE column, and gnark spends less
// on those. Both figures below are measured on gnark v0.15.0 with a distinct wire per
// query, which matters: reuse a query wire and the SCS builder folds the duplicates
// away, which reads as a much cheaper query than a real circuit ever gets.
//
//	                             per table entry    per query
//	two columns (the S-box)      1 R1CS / 5 PLONK   2 R1CS / 7 PLONK
//	one column (std/rangecheck)  1 R1CS / 3 PLONK   1 R1CS / 5 PLONK, plus one R1CS
//	                                                per checked value
//
// So sending the canonicity check to std/rangecheck buys a second table but halves its
// queries' R1CS cost, and std/rangecheck picks its own base width from how many checks
// it collected — which both keeps small circuits from paying for a table they cannot
// amortize and, for WordBits=8, cuts the limb count as well (a 128-bit check is 16
// byte-lookups through the S-box table, against 8-13 limbs at the base it chooses).
// Measured on BLS12-381 Davies-Meyer Merkle trees at n = 1, against routing the check
// back through the S-box table (R1CS / PLONK per node, at the tree size named):
//
//	              1 call          per node at 1023
//	w8   S-box     1011 / 3446     419 / 1721
//	w8   rchk      1025 / 3566     340 / 1436
//	w16  S-box    66227 / 329014   226 /  889
//	w16  rchk     66305 / 329390   212 /  860
//
// The single call pays 14-376 more for the extra table and the crossover is a few
// hundred calls, so this is the right default for the job workloads and marginally the
// wrong one for the bare-permutation column.
func (e *engine) bar(branch []frontend.Variable) []frontend.Variable {
	m := e.params.NumWords
	flat := make([]frontend.Variable, 0, len(branch)*m)
	for _, v := range branch {
		words := algebra.CanonicalDecomposeExternalWordRange(e.api, e.rchk, v, e.params.WordBits, m)
		for i := range words {
			words[i] = e.sbox.Lookup(words[i])[0] // binds the word to [0, 2^WordBits) AND applies the S-box
		}
		flat = append(flat, words...)
	}

	rot := e.params.Rot
	rotated := make([]frontend.Variable, len(flat))
	copy(rotated, flat[rot:])
	copy(rotated[len(flat)-rot:], flat[:rot])

	out := make([]frontend.Variable, len(branch))
	for i := range out {
		out[i] = algebra.RecomposeBE(e.api, rotated[i*m:(i+1)*m], e.params.WordBits)
	}
	return out
}
